#!/bin/bash
echo "Setup virtual environment"
echo "==> Create virtual environment"
python3.6 -m venv ./scripts/.virtualenv
source scripts/.virtualenv/bin/activate

echo "==> Install requirements"
pip3 install -r requirements.txt
