# third parties
from _typeshed import Incomplete

class DelayedQueue:
    delay_sec: Incomplete
    def __init__(self, delay) -> None: ...
    def put(self, element, delay: bool = ...) -> None: ...
    def close(self) -> None: ...
    def get(self): ...
    def remove(self, predicate): ...
