# standard library
from collections.abc import Generator

# third parties
from _typeshed import Incomplete

class DirectorySnapshotDiff:
    def __init__(self, ref, snapshot, ignore_device: bool = ...) -> None: ...
    @property
    def files_created(self): ...
    @property
    def files_deleted(self): ...
    @property
    def files_modified(self): ...
    @property
    def files_moved(self): ...
    @property
    def dirs_modified(self): ...
    @property
    def dirs_moved(self): ...
    @property
    def dirs_deleted(self): ...
    @property
    def dirs_created(self): ...

class DirectorySnapshot:
    recursive: Incomplete
    stat: Incomplete
    listdir: Incomplete
    def __init__(self, path, recursive: bool = ..., stat=..., listdir=...) -> None: ...
    def walk(self, root) -> Generator[Incomplete, None, None]: ...
    @property
    def paths(self): ...
    def path(self, id): ...
    def inode(self, path): ...
    def isdir(self, path): ...
    def mtime(self, path): ...
    def size(self, path): ...
    def stat_info(self, path): ...
    def __sub__(self, previous_dirsnap): ...

class EmptyDirectorySnapshot:
    @staticmethod
    def path(_) -> None: ...
    @property
    def paths(self): ...
