def name(item): ...
def is_classmethod(instancemethod, klass): ...
def is_static_method(method, klass): ...
def is_class_private_name(name): ...
def method_name(method): ...
def format_arg_value(arg_val): ...
def echo(fn, write=...): ...
def echo_instancemethod(klass, method, write=...) -> None: ...
def echo_class(klass, write=...) -> None: ...
def echo_module(mod, write=...) -> None: ...
