class AsyncExitStack:
    def __init__(self) -> None: ...
    def pop_all(self): ...
    def push(self, exit): ...
    def enter_context(self, cm): ...
    def callback(self, callback, *args, **kwds): ...
    async def enter_async_context(self, cm): ...
    def push_async_exit(self, exit): ...
    def push_async_callback(self, callback, *args, **kwds): ...
    async def aclose(self) -> None: ...
    async def __aenter__(self): ...
    async def __aexit__(self, *exc_details): ...
