from . import AlreadyLocked as AlreadyLocked, LockBase as LockBase, LockFailed as LockFailed, LockTimeout as LockTimeout, NotLocked as NotLocked, NotMyLock as NotMyLock
from _typeshed import Incomplete

class LinkLockFile(LockBase):
    def acquire(self, timeout: Incomplete | None = ...) -> None: ...
    def release(self) -> None: ...
    def is_locked(self): ...
    def i_am_locking(self): ...
    def break_lock(self) -> None: ...
