# third parties
from _typeshed import Incomplete

# relative
from . import AlreadyLocked as AlreadyLocked
from . import LockBase as LockBase
from . import LockFailed as LockFailed
from . import LockTimeout as LockTimeout
from . import NotLocked as NotLocked
from . import NotMyLock as NotMyLock

class PIDLockFile(LockBase):
    unique_name: Incomplete
    def __init__(
        self, path, threaded: bool = ..., timeout: Incomplete | None = ...
    ) -> None: ...
    def read_pid(self): ...
    def is_locked(self): ...
    def i_am_locking(self): ...
    def acquire(self, timeout: Incomplete | None = ...) -> None: ...
    def release(self) -> None: ...
    def break_lock(self) -> None: ...

def read_pid_from_pidfile(pidfile_path): ...
def write_pid_to_pidfile(pidfile_path) -> None: ...
def remove_existing_pidfile(pidfile_path) -> None: ...
