from . import AlreadyLocked as AlreadyLocked, LockBase as LockBase, LockTimeout as LockTimeout, NotLocked as NotLocked, NotMyLock as NotMyLock
from _typeshed import Incomplete

unicode = str

class SQLiteLockFile(LockBase):
    testdb: Incomplete
    lock_file: Incomplete
    unique_name: Incomplete
    connection: Incomplete
    def __init__(self, path, threaded: bool = ..., timeout: Incomplete | None = ...) -> None: ...
    def acquire(self, timeout: Incomplete | None = ...) -> None: ...
    def release(self) -> None: ...
    def is_locked(self): ...
    def i_am_locking(self): ...
    def break_lock(self) -> None: ...
