from _typeshed import Incomplete
from collections.abc import Generator

async def add_resource(source, cleanup_time) -> Generator[Incomplete, None, None]: ...
def assert_run(request): ...
def event_loop() -> Generator[Incomplete, None, Incomplete]: ...
