from _typeshed import Incomplete

logger: Incomplete
logger_ch: Incomplete
log_formatter: Incomplete
COWACTERS: Incomplete
EYES: Incomplete
NOT_SAFE_FOR_WORK_COWACTERS: Incomplete
NOT_SAFE_FOR_WORK_EYES: Incomplete

def get_cowacters(sfw: bool = ..., sort: bool = ...): ...
def get_eyes(sfw: bool = ..., sort: bool = ...): ...
def not_safe_for_work(cow: str = ..., eyes: str = ...): ...

class Cowacter:
    def __init__(self, eyes: str = ..., thoughts: bool = ..., tongue: bool = ..., body: Incomplete | None = ...) -> None: ...
    def milk(self, msg): ...

class Beavis(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class BongCow(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class BudFrogs(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Bunny(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Cheese(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Cower(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Daemon(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class DragonAndCow(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Eyes(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class FlamingSheep(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Ghostbusters(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class HeadInCow(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class HelloKitty(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Kiss(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Kitty(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Koala(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Kosh(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class LukeKoala(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class MechAndCow(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Meow(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Milk(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Moofasa(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Moose(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Mutilated(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Ren(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Satanic(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Sheep(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Skeleton(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Small(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Sodomized(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Squirrel(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Stegosaurus(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Stimpy(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Supermilker(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Surgery(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Telebears(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class ThreeEyes(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Turkey(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Turtle(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Tux(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Udder(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class VaderKoala(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class Vader(Cowacter):
    def __init__(self, **kwargs) -> None: ...

class www(Cowacter):
    def __init__(self, **kwargs) -> None: ...

def get_cow(name: str = ...): ...
def eye_options(): ...
def cow_options(): ...
def milk_random_cow(msg, sfw: bool = ...): ...
def main() -> None: ...
