# third parties
from _typeshed import Incomplete

# relative
from .xml import findtext as findtext

class MinioException(Exception): ...

class InvalidResponseError(MinioException):
    def __init__(self, code, content_type, body) -> None: ...
    def __reduce__(self): ...

class ServerError(MinioException):
    def __init__(self, message, status_code) -> None: ...
    @property
    def status_code(self): ...

class S3Error(MinioException):
    def __init__(
        self,
        code,
        message,
        resource,
        request_id,
        host_id,
        response,
        bucket_name: Incomplete | None = ...,
        object_name: Incomplete | None = ...,
    ) -> None: ...
    def __reduce__(self): ...
    @property
    def code(self): ...
    @property
    def message(self): ...
    @property
    def response(self): ...
    @classmethod
    def fromxml(cls, response): ...
    def copy(self, code, message): ...
