from . import time as time
from .helpers import queryencode as queryencode, sha256_hash as sha256_hash

SIGN_V4_ALGORITHM: str

def sign_v4_s3(method, url, region, headers, credentials, content_sha256, date): ...
def sign_v4_sts(method, url, region, headers, credentials, content_sha256, date): ...
def presign_v4(method, url, region, credentials, date, expires): ...
def get_credential_string(access_key, date, region): ...
def post_presign_v4(data, secret_key, date, region): ...
