from .commonconfig import Tags as Tags
from .xml import Element as Element, SubElement as SubElement, find as find

class Tagging:
    def __init__(self, tags) -> None: ...
    @property
    def tags(self): ...
    @classmethod
    def fromxml(cls, element): ...
    def toxml(self, element): ...
