# relative
from . import __LOCALE_LOCK__ as __LOCALE_LOCK__

def from_iso8601utc(value): ...
def to_iso8601utc(value): ...
def from_http_header(value): ...
def to_http_header(value): ...
def to_amz_date(value): ...
def utcnow(): ...
def to_signer_date(value): ...
