from _typeshed import Incomplete

def Element(tag, namespace=...): ...
def SubElement(parent, tag, text: Incomplete | None = ...): ...
def findall(element, name): ...
def find(element, name): ...
def findtext(element, name, strict: bool = ...): ...
def unmarshal(cls, xmlstring): ...
def getbytes(element): ...
def marshal(obj): ...
