import ctypes.util
from _typeshed import Incomplete
from watchdog.utils import UnsupportedLibc as UnsupportedLibc

libc: Incomplete
inotify_add_watch: Incomplete
inotify_rm_watch: Incomplete
inotify_init: Incomplete

class InotifyConstants:
    IN_ACCESS: int
    IN_MODIFY: int
    IN_ATTRIB: int
    IN_CLOSE_WRITE: int
    IN_CLOSE_NOWRITE: int
    IN_OPEN: int
    IN_MOVED_FROM: int
    IN_MOVED_TO: int
    IN_CREATE: int
    IN_DELETE: int
    IN_DELETE_SELF: int
    IN_MOVE_SELF: int
    IN_CLOSE: Incomplete
    IN_MOVE: Incomplete
    IN_UNMOUNT: int
    IN_Q_OVERFLOW: int
    IN_IGNORED: int
    IN_ONLYDIR: int
    IN_DONT_FOLLOW: int
    IN_EXCL_UNLINK: int
    IN_MASK_ADD: int
    IN_ISDIR: int
    IN_ONESHOT: int
    IN_ALL_EVENTS: Incomplete
    IN_CLOEXEC: int
    IN_NONBLOCK: int

WATCHDOG_ALL_EVENTS: Incomplete

class inotify_event_struct(ctypes.Structure): ...

EVENT_SIZE: Incomplete
DEFAULT_NUM_EVENTS: int
DEFAULT_EVENT_BUFFER_SIZE: Incomplete

class Inotify:
    def __init__(self, path, recursive: bool = ..., event_mask=...) -> None: ...
    @property
    def event_mask(self): ...
    @property
    def path(self): ...
    @property
    def is_recursive(self): ...
    @property
    def fd(self): ...
    def clear_move_records(self) -> None: ...
    def source_for_move(self, destination_event): ...
    def remember_move_from_event(self, event) -> None: ...
    def add_watch(self, path) -> None: ...
    def remove_watch(self, path) -> None: ...
    def close(self) -> None: ...
    def read_events(self, event_buffer_size=...): ...

class InotifyEvent:
    def __init__(self, wd, mask, cookie, name, src_path) -> None: ...
    @property
    def src_path(self): ...
    @property
    def wd(self): ...
    @property
    def mask(self): ...
    @property
    def cookie(self): ...
    @property
    def name(self): ...
    @property
    def is_modify(self): ...
    @property
    def is_close_write(self): ...
    @property
    def is_close_nowrite(self): ...
    @property
    def is_access(self): ...
    @property
    def is_delete(self): ...
    @property
    def is_delete_self(self): ...
    @property
    def is_create(self): ...
    @property
    def is_moved_from(self): ...
    @property
    def is_moved_to(self): ...
    @property
    def is_move(self): ...
    @property
    def is_move_self(self): ...
    @property
    def is_attrib(self): ...
    @property
    def is_ignored(self): ...
    @property
    def is_directory(self): ...
    @property
    def key(self): ...
    def __eq__(self, inotify_event): ...
    def __ne__(self, inotify_event): ...
    def __hash__(self): ...
