from watchdog.events import DirCreatedEvent as DirCreatedEvent, DirDeletedEvent as DirDeletedEvent, DirModifiedEvent as DirModifiedEvent, DirMovedEvent as DirMovedEvent, FileCreatedEvent as FileCreatedEvent, FileDeletedEvent as FileDeletedEvent, FileModifiedEvent as FileModifiedEvent, FileMovedEvent as FileMovedEvent, generate_sub_created_events as generate_sub_created_events, generate_sub_moved_events as generate_sub_moved_events
from watchdog.observers.api import BaseObserver as BaseObserver, DEFAULT_EMITTER_TIMEOUT as DEFAULT_EMITTER_TIMEOUT, DEFAULT_OBSERVER_TIMEOUT as DEFAULT_OBSERVER_TIMEOUT, EventEmitter as EventEmitter
from watchdog.observers.winapi import close_directory_handle as close_directory_handle, get_directory_handle as get_directory_handle, read_events as read_events

WATCHDOG_TRAVERSE_MOVED_DIR_DELAY: int

class WindowsApiEmitter(EventEmitter):
    def __init__(self, event_queue, watch, timeout=...) -> None: ...
    def on_thread_start(self) -> None: ...
    def start(self) -> None: ...
    def on_thread_stop(self) -> None: ...
    def queue_events(self, timeout) -> None: ...

class WindowsApiObserver(BaseObserver):
    def __init__(self, timeout=...) -> None: ...
