apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpm
  labels:
    app: webpm
spec:
  replicas: 2

  selector:
    matchLabels:
      app: webpm

  template:

    metadata:
      name: webpm
      labels:
        app: webpm
    spec:
      imagePullSecrets:
        - name: gitlab-docker
      containers:
        - name: main
          securityContext:
            readOnlyRootFilesystem: true
          env:
            - name: ROOT_REDIRECTION
              valueFrom:
                configMapKeyRef:
                  key: root_redirection
                  name: webpm
            - name: VERSION
              value: {{ .Chart.AppVersion }}
            - name: CONFIG_ID
              valueFrom:
                configMapKeyRef:
                  key: configID
                  name: webpm
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: webpm
            - name: OIDC_ISSUER
              valueFrom:
                configMapKeyRef:
                  key: oidc_issuer
                  name: webpm
            - name: ASSETS_GATEWAY_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: assets-gatewayBaseUrl
                  name: webpm
            - name: DEFAULT_CDN_CLIENT_VERSION
              valueFrom:
                configMapKeyRef:
                  key: default_cdn_client_version
                  name: webpm

            - name: CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: client_id
                  name: webpm
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: client_secret
                  name: webpm
          image: {{ printf "registry.gitlab.com/youwol/platform/webpm:%s" .Chart.AppVersion }}
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8000
              path: /observability/readiness
          livenessProbe:
            httpGet:
              port: 8000
              path: /observability/liveness
          startupProbe:
            httpGet:
              port: 8000
              path: /observability/startup
      restartPolicy: Always
