---

name: Continuous Integration

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      local-youwol-client_ref:
        description: >
          Branch, tag or SHA for local-youwol-client checkout.
          Default to 'main'
        default: main

      webpm-client_ref:
        description: >
          Branch, tag or SHA for webpm-client checkout.
          Default to 'main'
        default: main

      vsf-core_ref:
        description: >
          Branch, tag or SHA for vsf-core checkout.
          Default to 'main'
        default: main

      http-clients_ref:
        description: >
          Branch, tag or SHA for http-clients checkout.
          Default to 'main'
        default: main

      todo-app-ts_ref:
        description: >
          Branch, tag or SHA for todo-app-ts checkout.
          Default to 'main'
        default: main

      skip:
        description: |
          List of check to skip : local-youwol-client, http-clients, vsf-core,
          webpm-client, pipeline-ts, build, version_monotony, audit, pep8,
          cleanness, dep_manager
        required: false
        default: ''


  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  integration_local-youwol-client:
    name: Integration local-youwol-client
    if: "! contains(inputs.skip, 'local-youwol-client')"
    uses: youwol/nestor/.github/workflows/integration-tests.yaml@v3
    with:
      pyYouwolCoverage: true
      tsRepository: youwol/local-youwol-client
      tsRef: feature/typescript-5.3.3
      coverageOmit: '*/src/tests/*/yw_pipeline.py'
      name: local-youwol-client
    secrets: inherit

  integration_webpm-client:
    name: Integration webpm-client
    if: "! contains(inputs.skip, 'webpm-client')"
    uses: youwol/nestor/.github/workflows/integration-tests.yaml@v3
    with:
      pyYouwolCoverage: true
      tsRepository: youwol/webpm-client
      tsRef: feature/typescript-5.3.3
      name: webpm-client
    secrets: inherit

  integration_vsf-core:
    name: Integration vsf-core
    if: "! contains(inputs.skip, 'vsf-core')"
    uses: youwol/nestor/.github/workflows/integration-tests.yaml@v3
    with:
      pyYouwolCoverage: true
      tsRepository: youwol/vsf-core
      tsRef: feature/typescript-5.3.3
      name: vsf-core
    secrets: inherit

  integration_http-clients:
    name: Integration http-clients
    if: "! contains(inputs.skip, 'http-clients')"
    uses: youwol/nestor/.github/workflows/integration-tests.yaml@v3
    with:
      pyYouwolCoverage: true
      tsRepository: youwol/http-clients
      tsRef: feature/typescript-5.3.3
      name: http-clients
    secrets: inherit

  combine_coverages:
    name: Combine Coverages
    runs-on: ubuntu-latest
    needs:
      - integration_local-youwol-client
      - integration_webpm-client
      - integration_http-clients
      - integration_vsf-core
    steps:
      - name: Prepare repository
        id: prepare
        uses: youwol/nestor/py-youwol/prepare@v3

      - name: Combine
        id: combine
        uses: youwol/nestor/py-youwol/combine-coverages@v3

  pipeline_ts:
    name: Pipeline Typescript
    if: "! contains(inputs.skip, 'pipeline-ts')"
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repository
        id: prepare
        uses: youwol/nestor/py-youwol/prepare@v3

      - name: Prepare todo-app-ts repository
        id: prepare_todo-app-ts
        uses: youwol/nestor/ts/prepare@v3
        with:
          repository: youwol/todo-app-ts
          ref: feature/typescript-5.3.3
          path: ${{ runner.temp }}/todo-app-ts

      - name: Build todo-app-ts
        id: build_todo-app-ts
        uses: youwol/nestor/ts/build@v3
        with:
          skip: ${{ inputs.skip }}

  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repository
        id: prepare
        uses: youwol/nestor/py-youwol/prepare@v3

      - name: Checkout target branch
        id: checkout_target_branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: .py-youwol_target

      - name: Static Analysis
        id: static_analysis
        uses: youwol/nestor/py-youwol/static-analysis@v3
        with:
          targetBranchPath: .py-youwol_target
          skip: ${{ inputs.skip }}


  build:
    name: Build
    needs:
      - integration_local-youwol-client
      - integration_webpm-client
      - integration_vsf-core
      - integration_http-clients
      - static_analysis
      - pipeline_ts
    runs-on: ubuntu-latest
    if: "! contains(inputs.skip, 'build')"
    steps:
      - name: Prepare repository
        id: prepare
        uses: youwol/nestor/py-youwol/prepare@v3

      - name: Build
        id: build
        uses: youwol/nestor/py-youwol/build@v3
