# third parties
from _typeshed import Incomplete

def concat(source, task_limit: Incomplete | None = ...): ...
def flatten(source, task_limit: Incomplete | None = ...): ...
def switch(source): ...
def concatmap(source, func, *more_sources, task_limit: Incomplete | None = ...): ...
def flatmap(source, func, *more_sources, task_limit: Incomplete | None = ...): ...
def switchmap(source, func, *more_sources): ...
