from _typeshed import Incomplete
from collections.abc import Generator

async def accumulate(source, func=..., initializer: Incomplete | None = ...) -> Generator[Incomplete, None, None]: ...
def reduce(source, func, initializer: Incomplete | None = ...): ...
async def list(source) -> Generator[Incomplete, None, None]: ...
