# standard library
from collections.abc import Generator

# third parties
from _typeshed import Incomplete

async def accumulate(
    source, func=..., initializer: Incomplete | None = ...
) -> Generator[Incomplete, None, None]: ...
def reduce(source, func, initializer: Incomplete | None = ...): ...
async def list(source) -> Generator[Incomplete, None, None]: ...
