# standard library
from collections.abc import Generator

# third parties
from _typeshed import Incomplete

async def spaceout(source, interval) -> Generator[Incomplete, None, None]: ...
async def timeout(source, timeout) -> Generator[Incomplete, None, None]: ...
async def delay(source, delay) -> Generator[Incomplete, None, None]: ...
