from .combine import map as map
from _typeshed import Incomplete
from collections.abc import Generator

async def enumerate(source, start: int = ..., step: int = ...) -> Generator[Incomplete, None, None]: ...
def starmap(source, func, ordered: bool = ..., task_limit: Incomplete | None = ...): ...
async def cycle(source) -> Generator[Incomplete, None, None]: ...
async def chunks(source, n) -> Generator[Incomplete, None, None]: ...
