# standard library
from collections.abc import Generator

# third parties
from _typeshed import Incomplete

# relative
from .combine import map as map

async def enumerate(
    source, start: int = ..., step: int = ...
) -> Generator[Incomplete, None, None]: ...
def starmap(source, func, ordered: bool = ..., task_limit: Incomplete | None = ...): ...
async def cycle(source) -> Generator[Incomplete, None, None]: ...
async def chunks(source, n) -> Generator[Incomplete, None, None]: ...
